# Generated by Django 6.0.2 on 2026-06-06 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_address_proof_customer_id_proof_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['customer', 'account_type']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='idx_account_number'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['customer', 'account_type'], name='idx_account_customer_type'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='idx_account_active'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['customer', '-opened_at'], name='idx_account_customer_opened'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_status'], name='idx_customer_kyc'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='idx_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['id_number'], name='idx_customer_id'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['risk_tier'], name='idx_customer_risk'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['aml_flagged'], name='idx_customer_aml'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_status', 'risk_tier'], name='idx_customer_kyc_risk'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='idx_customer_created'),
        ),
    ]
