# Generated by Django 6.0.2 on 2026-06-06 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='idx_account_number',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='idx_account_customer_type',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='idx_account_active',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='idx_account_customer_opened',
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('RWF', 'Rwandan Franc'), ('USD', 'US Dollar')], default='RWF', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
