# Generated by Django 6.0.2 on 2026-06-06 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options_alter_customer_options_and_more'),
        ('banking', '0002_complianceflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankingtransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='complianceflag',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='bankingtransaction',
            index=models.Index(fields=['-timestamp'], name='idx_banking_timestamp'),
        ),
        migrations.AddIndex(
            model_name='bankingtransaction',
            index=models.Index(fields=['fraud_prediction'], name='idx_banking_fraud_pred'),
        ),
        migrations.AddIndex(
            model_name='bankingtransaction',
            index=models.Index(fields=['transaction_type'], name='idx_banking_tx_type'),
        ),
        migrations.AddIndex(
            model_name='bankingtransaction',
            index=models.Index(fields=['from_account', '-timestamp'], name='idx_banking_from_account'),
        ),
        migrations.AddIndex(
            model_name='bankingtransaction',
            index=models.Index(fields=['to_account', '-timestamp'], name='idx_banking_to_account'),
        ),
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['resolved', '-created_at'], name='idx_compliance_unresolved'),
        ),
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['customer'], name='idx_compliance_customer'),
        ),
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['reason'], name='idx_compliance_reason'),
        ),
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['-created_at'], name='idx_compliance_created'),
        ),
    ]
