# Generated by Django 6.0.2 on 2026-06-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_and_more'),
        ('banking', '0003_alter_bankingtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingtransaction',
            name='amount_deviation_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='amount_ratio_to_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='days_since_last_password_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='days_since_last_transaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='days_since_profile_update',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='hours_since_last_login',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='transaction_count_last_24h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='transaction_day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='transaction_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='transaction_value_last_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bankingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AddIndex(
            model_name='bankingtransaction',
            index=models.Index(fields=['transaction_hour'], name='idx_banking_hour'),
        ),
        migrations.AddIndex(
            model_name='bankingtransaction',
            index=models.Index(fields=['amount_ratio_to_avg'], name='idx_banking_ratio'),
        ),
    ]
