# Generated by Django 6.0.2 on 2026-06-06 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-timestamp'], name='idx_demo_timestamp'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['prediction'], name='idx_demo_prediction'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_number'], name='idx_demo_account'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-timestamp', 'prediction'], name='idx_demo_timestamp_pred'),
        ),
    ]
